config/routes.rb
Rails.application.routes.draw do
  resources :customers
  devise_for :users
  resources :orders
  resources :pages
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'
  scope 'checkout' do
  post 'create', to: 'checkout#create', as: 'checkout_create'
  get 'success', to: 'checkout#success', as: 'checkout_success'
  get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  get 'test', to: 'checkout#test', as: 'checkout_test'
end
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  get 'welcome' => 'welcome#index'

  get 'products' => 'products#index', as: 'products'

  get 'products/:id' => 'products#show', as: 'product'

  get 'static/:permalink' => 'pages#static', as: 'static'

  get 'search' => 'products#search', as: 'search'

  get 'categories' => 'categories#show', as: 'categories'

  get 'cart' => 'cart#show', as: 'cart'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/administrator.rb
class Administrator < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :category
  accepts_nested_attributes_for :category, allow_destroy:  true
  validates :name, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :customer
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @cats
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController #InheritedResources::Base

  # private

  # def page_params
  #   params.require(:page).permit(:title, :content, :permalink)
  #  end

  def static
    @page = Page.find_by(permalink: params[:permalink])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :initialize_session
  before_action :load_cart
  def index
    # @products = Product.all
    @products = Product.order("name").page(params[:page]).per(5)
    @categories = Category.all
  end

  def show
    @products = Product.find(params[:id])
  end

  def search
    if params[:category] == '5'
      @products = Product.where("name LIKE ?", "%#{params[:search_term]}%")
    else
      @products = Product.where("name LIKE ?", "%#{params[:search_term]}%").where("category_id=?",params[:category])
    end
  end

  def add_to_cart
    id = params[:id].to_i

    session[:cart] << id unless session[:cart].include?(id)
    redirect_to products_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to cart_path
  end

  def load_cart
    @cart = Product.find(session[:cart])
  end

  def initialize_session
    session[:cart] ||= []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/products/_product.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <div class="card" style="width: 18rem;">
        <%= link_to product_path(product) do %>
          <%= image_tag product.image, :class => "card-img-top", :size => '270x230' %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted">CDN$<%= product.price %></h6>
          <p class="card-text"><%= product.description %></p>
          <% if @cart.include?(product)%>
            <button type="button" class="btn btn-primary" disabled>Add To Cart</button>
          <%else %>
          <%= button_to 'Add To Cart', add_to_cart_path(product.id), method: :post, :class =>'btn btn-primary' %>
           <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/_searchform.html.erb
<%= form_with(url: search_path, local: true,  method: "get", :class => "form-control mr-sm-2") do %>
  <%= text_field_tag(:search_term) %>
  <%= select_tag :category, options_from_collection_for_select(@cats, 'id', 'name'), :class => "btn btn-secondary dropdown-toggle" %>
  <%= submit_tag("Search", :class => "btn btn-outline-success my-2 my-sm-0") %>
<% end %>

app/views/products/index.html.erb
<div class="card-columns">
<%= render @products  %>
  <%= paginate @products  %>
</div>

<%= debug session[:cart] %>

app/views/products/search.html.erb
<div class="col-sm-6">
  <div class="card" style="width: 18rem;">
    <%= render partial: 'products/product',
               collection: @products,
               locals: {show_link: true} %>
  </div>
</div>

app/views/products/show.html.erb
<%= render @products %>

<p>
  <strong>Name:</strong>
  <%= @products.name %>
</p>